kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: echo-role-binding
  namespace: echo-ns
subjects:
  - kind: ServiceAccount
    name: echo
    namespace: echo-ns
roleRef:
  kind: Role
  name: echo-role
  apiGroup: rbac.authorization.k8s.io